name: Emscripten

on: [push, pull_request]

jobs:
  emscripten-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        build_type: [Debug, Release]
        exclude:
          # Exclude MacOS-Release
          - os: macos-latest
            build_type: Release
        include:
          - os: windows-latest
            host_name: Win10
          - os: ubuntu-latest
            host_name: Linux
          - os: macos-latest
            host_name: MacOS

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.host_name }} -> Emscripten, ${{ matrix.build_type }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Download and Configure Emscripten SDK
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/BuildTools/Scripts/github_actions
        if [[ "${{ matrix.host_name }}" != "Win"* ]]; then
          chmod +x emscripten_sdk.sh
        fi
        ./emscripten_sdk.sh "${{runner.workspace}}" 

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/BuildTools/Scripts/github_actions
        if [[ "${{ matrix.host_name }}" != "Win"* ]]; then
          chmod +x configure_cmake.sh
        fi
        ./configure_cmake.sh "emscripten" "${{runner.workspace}}" ${{ matrix.build_type }} "-DDILIGENT_BUILD_CORE_TESTS=ON"

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build .
