name: iOS

on: [push, pull_request]

jobs:
  build-ios-clang:
    strategy:
      matrix:
        config: [Debug, Release]

    runs-on: macos-latest
    name: iOS, ${{ matrix.config }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Format validation
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/BuildTools/FormatValidation
        ./validate_format_mac.sh

    - name: Download Vulkan SDK
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/BuildTools/Scripts/github_actions
        chmod +x vulkan_sdk.sh
        ./vulkan_sdk.sh

    - name: Configure CMake
      if: success()
      working-directory: ${{runner.workspace}}
      shell: bash
      run: |
        mkdir build
        cd ./build
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DDILIGENT_BUILD_TESTS=ON -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DCMAKE_OSX_ARCHITECTURES=arm64 -DVULKAN_SDK="${{ env.VULKAN_SDK }}" -DDILIGENT_NO_FORMAT_VALIDATION=ON -DCMAKE_INSTALL_PREFIX=install ..

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} --target install

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: ${{ success() && matrix.config == 'Release' }}
      with:
        name: DiligentCore-iOS-arm64-${{ matrix.config }}
        path: |
          ${{runner.workspace}}/build/install/
          !${{runner.workspace}}/build/install/**/*.a
        retention-days: 90
