name: UWP

on: [push, pull_request]

jobs:
  build-uwp:
    strategy:
      matrix:
        toolset: [x64]
        config: [Debug, Release]

    runs-on: windows-latest
    name: UWP, ${{ matrix.config }} ${{ matrix.toolset }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Format validation
      shell: cmd
      run: |
        cd BuildTools\FormatValidation
        validate_format_win.bat

    - name: Configure CMake
      if: success()
      working-directory: ${{runner.workspace}}
      shell: bash
      run: |
        mkdir build
        cd ./build
        cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -A ${{ matrix.toolset }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DDILIGENT_NO_FORMAT_VALIDATION=ON -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0 -DCMAKE_INSTALL_PREFIX=install .

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} --target install

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: ${{ success() && matrix.config == 'Release' }}
      with:
        name: DiligentCore-UWP-${{ matrix.toolset }}-VS2019-${{ matrix.config }}
        path: |
          ${{runner.workspace}}/build/install/
          !${{runner.workspace}}/build/install/**/*.lib
        retention-days: 90
